#!/bin/bash

publish_files=("data/" "source")
lib_file_prefix=("lib" "darts.rb" "helpers" "spec")

echo_line() {
  echo "${0##*/} ********************************************"
}

publish() {
  echo "rake publish --------------------"
  rake publish
}

spec() {
  echo "rspec spec/* --------------------"
  rspec spec/*
  [ "$?" -ne 0 ] && echo "Test Failed!!" && echo_line && exit 1
}

is_commited() {
  start_id=$1
  end_id=$2
  filenames=(${@:3})

  for filename in "${filenames[@]}"
  do
    count=$( git log --name-only ${start_id}..${end_id} | grep -c ${filename} )
    echo "${filename} : ${count}" 1>&2
    [ "${count}" -gt 0 ] && echo 1 && return
  done
  echo 0
}

echo_line

while read local_ref local_sha remote_ref remote_sha; do
  echo $local_ref
  echo $local_sha
  echo $remote_ref
  echo $remote_sha
  # master へのpushのみ適用
  if [ "$local_ref" == "refs/heads/master" ] && [ "$remote_ref" == "refs/heads/master" ]; then
    if [ -n "${remote_sha}" ] && [ -n "${local_sha}" ]; then
      # lib 以下に更新があるか（テスト実行対象か）
      commited_lib=$( is_commited ${remote_sha} ${local_sha} ${lib_file_prefix[@]} )
      echo "lib commited: ${commited_lib}"
      [ "${commited_lib}" == 1 ] && spec

      # source以下に更新があるか（midleman deployの対象か）
      commited_publish=$( is_commited ${remote_sha} ${local_sha} ${publish_files[@]} )
      echo "source commited: ${commited_publish}"
      [ "${commited_publish}" == 1 ] && publish
    fi
  fi
  echo_line
done

exit 0


